"""Universe repository ports."""
from __future__ import annotations

import builtins
from typing import Any, Protocol
from uuid import UUID

from src.universe.domain.entities import (
    Achievement,
    CareerPreferences,
    Certification,
    Course,
    Education,
    Experience,
    Interest,
    Language,
    Project,
    Skill,
)
from src.universe.domain.universe import Universe


class UniverseRepository(Protocol):
    async def get(self, user_id: UUID) -> Universe | None: ...
    async def save(self, universe: Universe) -> None: ...


class EducationRepository(Protocol):
    async def list(self, user_id: UUID) -> builtins.list[Education]: ...
    async def get(self, user_id: UUID, entity_id: UUID) -> Education | None: ...
    async def add(self, entity: Education) -> None: ...
    async def update(self, entity: Education) -> None: ...
    async def delete(self, user_id: UUID, entity_id: UUID) -> bool: ...
    async def update_embedding(self, entity_id: UUID, embedding: builtins.list[float]) -> None: ...


class ExperienceRepository(Protocol):
    async def list(self, user_id: UUID) -> builtins.list[Experience]: ...
    async def get(self, user_id: UUID, entity_id: UUID) -> Experience | None: ...
    async def add(self, entity: Experience) -> None: ...
    async def update(self, entity: Experience) -> None: ...
    async def delete(self, user_id: UUID, entity_id: UUID) -> bool: ...
    async def update_embedding(self, entity_id: UUID, embedding: builtins.list[float]) -> None: ...


class ProjectRepository(Protocol):
    async def list(self, user_id: UUID) -> builtins.list[Project]: ...
    async def get(self, user_id: UUID, entity_id: UUID) -> Project | None: ...
    async def add(self, entity: Project) -> None: ...
    async def update(self, entity: Project) -> None: ...
    async def delete(self, user_id: UUID, entity_id: UUID) -> bool: ...
    async def update_embedding(self, entity_id: UUID, embedding: builtins.list[float]) -> None: ...


class SkillRepository(Protocol):
    async def list(self, user_id: UUID) -> builtins.list[Skill]: ...
    async def get(self, user_id: UUID, entity_id: UUID) -> Skill | None: ...
    async def add(self, entity: Skill) -> None: ...
    async def update(self, entity: Skill) -> None: ...
    async def delete(self, user_id: UUID, entity_id: UUID) -> bool: ...
    async def update_embedding(self, entity_id: UUID, embedding: builtins.list[float]) -> None: ...
    async def find_by_name(self, user_id: UUID, name: str) -> Skill | None: ...


class CertificationRepository(Protocol):
    async def list(self, user_id: UUID) -> builtins.list[Certification]: ...
    async def get(self, user_id: UUID, entity_id: UUID) -> Certification | None: ...
    async def add(self, entity: Certification) -> None: ...
    async def update(self, entity: Certification) -> None: ...
    async def delete(self, user_id: UUID, entity_id: UUID) -> bool: ...
    async def update_embedding(self, entity_id: UUID, embedding: builtins.list[float]) -> None: ...


class CourseRepository(Protocol):
    async def list(self, user_id: UUID) -> builtins.list[Course]: ...
    async def get(self, user_id: UUID, entity_id: UUID) -> Course | None: ...
    async def add(self, entity: Course) -> None: ...
    async def update(self, entity: Course) -> None: ...
    async def delete(self, user_id: UUID, entity_id: UUID) -> bool: ...


class LanguageRepository(Protocol):
    async def list(self, user_id: UUID) -> builtins.list[Language]: ...
    async def get(self, user_id: UUID, entity_id: UUID) -> Language | None: ...
    async def add(self, entity: Language) -> None: ...
    async def update(self, entity: Language) -> None: ...
    async def delete(self, user_id: UUID, entity_id: UUID) -> bool: ...


class AchievementRepository(Protocol):
    async def list(self, user_id: UUID) -> builtins.list[Achievement]: ...
    async def get(self, user_id: UUID, entity_id: UUID) -> Achievement | None: ...
    async def add(self, entity: Achievement) -> None: ...
    async def update(self, entity: Achievement) -> None: ...
    async def delete(self, user_id: UUID, entity_id: UUID) -> bool: ...


class InterestRepository(Protocol):
    async def list(self, user_id: UUID) -> builtins.list[Interest]: ...
    async def get(self, user_id: UUID, entity_id: UUID) -> Interest | None: ...
    async def add(self, entity: Interest) -> None: ...
    async def update(self, entity: Interest) -> None: ...
    async def delete(self, user_id: UUID, entity_id: UUID) -> bool: ...


class CareerPreferencesRepository(Protocol):
    async def get(self, user_id: UUID) -> CareerPreferences | None: ...
    async def upsert(self, prefs: CareerPreferences) -> None: ...


class SemanticSearchPort(Protocol):
    async def search(
        self,
        *,
        user_id: UUID,
        embedding: builtins.list[float],
        top_k: int = 30,
        entity_types: builtins.list[str] | None = None,
    ) -> builtins.list[dict[str, Any]]:
        """Return list of {entity_type, entity_id, score, fields}."""
        ...


class EmbeddingRefreshScheduler(Protocol):
    async def enqueue(self, *, entity_type: str, entity_id: UUID) -> None: ...
