"""Text2Cypher — Natural language → openCypher for Apache AGE.

Sprint R introduces structured graph queries generated by LLMs so the agent
can reason about trajectories, implicit skills, and ESCO-based gaps without
relying solely on vector similarity.

Architecture:
  1. Schema descriptor — auto-built from graph/domain/schema.py
  2. LLM prompt — system prompt with schema + AGE 1.5 constraints
  3. Generation — single-shot LLM call (fast, cheap model)
  4. Validation — regex-based sanity checks + AGE-specific restrictions
  5. Execution — run against AGE with timeout, return structured results

Gupta & Tadayon (2026) report >90% accuracy for text-to-Cypher with a
well-schematised prompt; our domain is narrower (career graph only) so we
target 95%+ for common queries.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any, cast
from uuid import UUID

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

from src.graph.application.ports.age import cypher
from src.graph.domain import schema as graph_schema
from src.shared.config import get_settings
from src.shared.llm_client import anthropic_text

logger = structlog.get_logger(__name__)


def _count_return_columns(cypher_query: str) -> int:
    """Count top-level projected columns in the final RETURN clause.

    Splits on the last `RETURN`, strips trailing ORDER BY / SKIP / LIMIT, then
    counts commas at bracket/paren/brace depth 0 (so commas inside collect([...])
    or map literals aren't miscounted). Falls back to 1 when undeterminable, and
    caps at 16. Used to build matching AGE `AS (... agtype)` column defs.
    """
    returns = list(re.finditer(r"\breturn\b", cypher_query, re.IGNORECASE))
    if not returns:
        return 1
    tail = cypher_query[returns[-1].end():]
    lowered = tail.lower()
    cut = len(tail)
    for kw in (" order by ", " limit ", " skip "):
        idx = lowered.find(kw)
        if idx != -1:
            cut = min(cut, idx)
    tail = tail[:cut]
    depth = 0
    cols = 1
    for ch in tail:
        if ch in "([{":
            depth += 1
        elif ch in ")]}":
            depth = max(0, depth - 1)
        elif ch == "," and depth == 0:
            cols += 1
    return min(max(cols, 1), 16)


# Schema descriptor

_PERSONAL_NODE_SCHEMA = """
(:Experience {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:Education   {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:Skill      {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:Project    {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:Certification {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:Course     {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:Language   {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:Achievement {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:Interest   {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:Artifact   {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:ArchitectureDecision {id, user_id, kind, created_at, updated_at, valid_from, valid_to, confidence, source})
(:MergeEvent {id, user_id, kind, representative_id, merged_ids, merged_at, source})
"""

_ONTOLOGY_NODE_SCHEMA = """
(:Occupation {code, preferredLabel, altLabels, description, isco_group})
(:EscoSkill {code, preferredLabel, altLabels, description, hierarchy})
(:ISCOGroup {code, preferredLabel})
"""

_EDGE_SCHEMA = """
# Personal edges
(:Experience)-[:USES_TECH {valid_from, valid_to, confidence, source}]->(:Skill)
(:Project)-[:PART_OF {valid_from, valid_to, confidence, source}]->(:Experience)
(:Skill)-[:DERIVED_FROM {valid_from, valid_to, confidence, source}]->(:Project|Course)
(:Entity)-[:TOUCHED_IN {valid_from, valid_to, confidence, source}]->(:Episode)
(:Entity)-[:MEMBER_OF {valid_from, valid_to, confidence, source}]->(:Community)
(:Entity)-[:RELATED_TO {valid_from, valid_to, confidence, source, relation_label}]->(:Entity)
(:ArchitectureDecision)-[:SUPERSEDES {valid_from, valid_to, confidence, source}]->(:ArchitectureDecision)

# Ontology edges (read-only)
(:EscoSkill)-[:SKOS_BROADER]->(:EscoSkill)
(:EscoSkill)-[:SKOS_NARROWER]->(:EscoSkill)
(:EscoSkill)-[:ESSENTIAL_FOR {weight}]->(:Occupation)
(:EscoSkill)-[:OPTIONAL_FOR {weight}]->(:Occupation)
(:Occupation)-[:ISCO_GROUP_OF]->(:ISCOGroup)
"""

_AGE_CONSTRAINTS = """
Apache AGE 1.5 constraints — NEVER generate unsupported syntax:
  • DO NOT use: relationships(), ALL(), ANY(), FILTER(), EXTRACT(), REDUCE()
  • DO NOT use multiple labels (e.g. :Experience:Skill)
  • Variable-length paths: use -[*1..3]- (numeric range only)
  • Use properties(n) to get node properties as a map
  • Date comparisons: use datetime($date) for parameters
  • Aggregation: count(), collect() are supported
  • MERGE … ON CREATE SET / ON MATCH SET — NOT supported; use COALESCE instead
"""

_SYSTEM_PROMPT = f"""You are an expert openCypher query writer for Apache AGE 1.5 running on PostgreSQL 16.

Your job: translate a user's natural-language question into a valid, efficient openCypher query.

## Graph Schema

### Personal graph (`{graph_schema.GRAPH_PERSONAL}`)
{_PERSONAL_NODE_SCHEMA}

### Ontology graph (`{graph_schema.GRAPH_ONTOLOGY}`)
{_ONTOLOGY_NODE_SCHEMA}

### Edges
{_EDGE_SCHEMA}

## Query Rules
1. ALWAYS filter personal-graph nodes by `user_id = $user_id`.
2. For active (non-deleted) entities, add: `WHERE n.valid_to IS NULL`.
3. When querying the ontology graph (`{graph_schema.GRAPH_ONTOLOGY}`), do NOT filter by user_id.
4. Use parameters ($paramName) for literal values; never interpolate strings.
5. Return specific properties or aggregations; avoid returning full nodes unless asked.
6. Add `LIMIT 50` unless the user explicitly asks for "all" or "count".

## AGE 1.5 Constraints
{_AGE_CONSTRAINTS}

## Output format
Respond with ONLY a JSON object:
{{"cypher": "MATCH ...", "params": {{"user_id": "...", ...}}, "explanation": "brief description"}}

If the question cannot be answered with the available schema, return:
{{"cypher": null, "params": null, "explanation": "Cannot answer: reason"}}
"""


# Result types


@dataclass(frozen=True)
class CypherResult:
    cypher: str | None
    params: dict[str, Any]
    explanation: str
    rows: list[dict[str, Any]] | None = None
    error: str | None = None
    latency_ms: float = 0.0


# Validation


# AGE 1.5 lacks these functions; nodes()/shortestPath() were missing from the
# original list and would 500 at execution — reject them up front instead.
_AGE_FORBIDDEN = re.compile(
    r"\b(relationships|nodes|shortestPath|allShortestPaths|ALL|ANY|FILTER"
    r"|EXTRACT|REDUCE|FOREACH|CALL)\s*\(",
    re.IGNORECASE,
)
# query_graph is a READ path — any mutation keyword is rejected (defence in
# depth; the executor would also need write grants, but fail closed here).
_WRITE_KEYWORDS = re.compile(
    r"\b(CREATE|MERGE|SET|DELETE|REMOVE|DETACH)\b", re.IGNORECASE
)
# A raw UUID literal in generated Cypher means the model inlined an id instead
# of binding it as a param — on the personal graph that is the cross-tenant
# attack vector (e.g. `{user_id: '<victim-uuid>'}`), so reject it.
_UUID_LITERAL = re.compile(
    r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
)
# user_id must be BOUND to the server param ($user_id), not merely mentioned —
# matches both the map form `{user_id: $user_id}` and `WHERE n.user_id = $user_id`.
_USER_ID_BOUND = re.compile(r"user_id\s*[:=]\s*\$user_id")
# Capture node labels `(:Label)` / `(v:Label)` and edge types `[:T]` / `[r:T]`.
_NODE_LABEL_RE = re.compile(
    r"\(\s*(?:[A-Za-z_][A-Za-z0-9_]*)?\s*:\s*([A-Za-z_][A-Za-z0-9_]*)"
)
_EDGE_TYPE_RE = re.compile(
    r"\[\s*(?:[A-Za-z_][A-Za-z0-9_]*)?\s*:\s*([A-Za-z_][A-Za-z0-9_]*)"
)
# Personal-graph tenant scoping: EVERY node pattern must bind user_id to the
# server param. A single global "is $user_id mentioned?" check is bypassable —
# `MATCH (a:Skill {user_id:$user_id}) MATCH (b:Experience) RETURN b` scopes only
# `a` yet reads every tenant's Experience nodes (RLS does not cover AGE tables).
# Node patterns are parens NOT preceded by an identifier char (those are
# function calls like count(...)); a node is scoped if it carries
# `user_id: $user_id` in its own map OR its variable is constrained by a
# `WHERE <var>.user_id = $user_id` clause.
_NODE_PATTERN_RE = re.compile(r"(?<![A-Za-z0-9_])\(([^()]*)\)")
_NODE_VAR_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)")
_INLINE_USER_SCOPE = re.compile(r"user_id\s*:\s*\$user_id")


def _personal_scope_error(query: str) -> str | None:
    """Return an error if any personal-graph node pattern is not bound to
    $user_id. Fail closed — the contract (system prompt Rule 1) requires
    scoping every personal node; an unscoped node is a cross-tenant read."""
    if not _USER_ID_BOUND.search(query):
        return "tenant scope missing: personal-graph query must bind user_id = $user_id"
    for m in _NODE_PATTERN_RE.finditer(query):
        inner = m.group(1).strip()
        if not inner:
            continue  # anonymous () waypoint — cannot be returned, no leak
        if _INLINE_USER_SCOPE.search(inner):
            continue
        var_m = _NODE_VAR_RE.match(inner)
        var = var_m.group(1) if var_m else None
        if var and re.search(rf"\b{re.escape(var)}\.user_id\s*=\s*\$user_id", query):
            continue
        return (
            "tenant scope missing: every personal-graph node must bind "
            "user_id = $user_id (unscoped node pattern)"
        )
    return None


def _validate_query(query: str, *, graph: str) -> str | None:
    """Return an error message if *query* violates AGE/security constraints.

    Layers, fail-closed: (1) AGE-unsupported syntax, (2) single-statement,
    (3) read-only, (4) ontology allowlist (no unknown labels/edge types),
    (5) tenant scope on the personal graph — the user_id property filter is the
    ONLY isolation boundary because RLS does not cover AGE label tables.
    """
    if not query.strip():
        return "empty query"
    forbidden = _AGE_FORBIDDEN.search(query)
    if forbidden:
        return f"forbidden AGE function/keyword: {forbidden.group(0)}"
    if ";" in query:
        return "multiple statements not allowed"
    write = _WRITE_KEYWORDS.search(query)
    if write:
        return f"write operations are not allowed on graph reads: {write.group(0)}"
    for m in _NODE_LABEL_RE.finditer(query):
        if m.group(1) not in graph_schema.ALL_VERTEX_LABELS:
            return f"unknown vertex label: {m.group(1)}"
    for m in _EDGE_TYPE_RE.finditer(query):
        if m.group(1) not in graph_schema.ALL_EDGE_TYPES:
            return f"unknown edge type: {m.group(1)}"
    if graph == graph_schema.GRAPH_PERSONAL:
        scope_err = _personal_scope_error(query)
        if scope_err:
            return scope_err
        if _UUID_LITERAL.search(query):
            return "literal id not allowed: bind ids via $params, never inline UUIDs"
    return None


# Engine


class Text2CypherEngine:
    """Generate and execute openCypher from natural language."""

    def __init__(self, session: AsyncSession, user_id: UUID) -> None:
        self._session = session
        self._user_id = user_id
        self._settings = get_settings()

    async def generate(
        self, question: str, graph: str = graph_schema.GRAPH_PERSONAL
    ) -> CypherResult:
        """Generate Cypher from *question*.  Does NOT execute."""
        import time

        start = time.perf_counter()

        # Build the prompt
        messages = [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": question},
        ]

        # Call LLM
        try:
            llm_response = await self._call_llm(messages)
        except Exception as exc:
            logger.warning("text2cypher_llm_failed", error=str(exc))
            return CypherResult(
                cypher=None, params={}, explanation=f"LLM error: {exc}", latency_ms=0.0
            )

        # Parse JSON
        try:
            parsed = json.loads(llm_response)
            cypher_str = parsed.get("cypher")
            params = parsed.get("params", {})
            explanation = parsed.get("explanation", "")
        except json.JSONDecodeError:
            # Fallback: try to extract JSON from markdown fence
            fence_match = re.search(r"```json\s*(.*?)\s*```", llm_response, re.DOTALL)
            if fence_match:
                try:
                    parsed = json.loads(fence_match.group(1))
                    cypher_str = parsed.get("cypher")
                    params = parsed.get("params", {})
                    explanation = parsed.get("explanation", "")
                except json.JSONDecodeError:
                    return CypherResult(
                        cypher=None,
                        params={},
                        explanation="LLM returned invalid JSON",
                        latency_ms=(time.perf_counter() - start) * 1000,
                    )
            else:
                return CypherResult(
                    cypher=None,
                    params={},
                    explanation="LLM returned invalid JSON",
                    latency_ms=(time.perf_counter() - start) * 1000,
                )

        if not cypher_str:
            return CypherResult(
                cypher=None,
                params=params,
                explanation=explanation,
                latency_ms=(time.perf_counter() - start) * 1000,
            )

        # Force the server-bound tenant id — NEVER trust the LLM's user_id.
        # Dropping any model-supplied value closes the param-override vector;
        # the validator additionally rejects inline UUID literals.
        params = dict(params)
        params.pop("user_id", None)
        params["user_id"] = str(self._user_id)

        # Validate (AGE syntax + read-only + ontology allowlist + tenant scope)
        validation_err = _validate_query(cypher_str, graph=graph)
        if validation_err:
            return CypherResult(
                cypher=cypher_str,
                params=params,
                explanation=f"Generated but invalid: {validation_err}",
                error=validation_err,
                latency_ms=(time.perf_counter() - start) * 1000,
            )

        return CypherResult(
            cypher=cypher_str,
            params=params,
            explanation=explanation,
            latency_ms=(time.perf_counter() - start) * 1000,
        )

    async def execute(
        self, result: CypherResult, graph: str = graph_schema.GRAPH_PERSONAL
    ) -> CypherResult:
        """Execute a generated CypherResult against AGE."""
        if result.cypher is None or result.error:
            return result

        import time

        start = time.perf_counter()
        try:
            # The system prompt encourages multi-column projections
            # (`RETURN n.name, n.confidence`), but AGE requires the AS(...) column
            # arity to match. Derive it from the RETURN clause instead of
            # hardcoding a single column (which 'number of columns' errored).
            n_cols = _count_return_columns(result.cypher)
            col_names = ["result"] if n_cols <= 1 else [f"col{i}" for i in range(n_cols)]
            column_defs = ", ".join(f"{c} agtype" for c in col_names)

            rows = await cypher(
                self._session,
                graph,
                result.cypher,
                params=result.params,
                column_defs=column_defs,
            )
            from src.graph.application.ports.age import parse_agtype

            def _p(v: Any) -> Any:
                return parse_agtype(v) if v is not None else None

            parsed_rows = []
            for r in rows:
                if n_cols <= 1:
                    parsed_rows.append(_p(r.get("result")))
                else:
                    parsed_rows.append({c: _p(r.get(c)) for c in col_names})

            latency = result.latency_ms + (time.perf_counter() - start) * 1000
            return CypherResult(
                cypher=result.cypher,
                params=result.params,
                explanation=result.explanation,
                rows=parsed_rows,
                latency_ms=latency,
            )
        except Exception as exc:
            logger.warning("text2cypher_execution_failed", error=str(exc), cypher=result.cypher)
            latency = result.latency_ms + (time.perf_counter() - start) * 1000
            return CypherResult(
                cypher=result.cypher,
                params=result.params,
                explanation=result.explanation,
                error=str(exc),
                latency_ms=latency,
            )

    async def ask(self, question: str, graph: str = graph_schema.GRAPH_PERSONAL) -> CypherResult:
        """Generate + execute in one call."""
        gen = await self.generate(question, graph)
        return await self.execute(gen, graph)

    async def _call_llm(self, messages: list[dict[str, str]]) -> str:
        """Route to the configured LLM provider."""
        provider = self._settings.agents_provider_resolved
        if provider == "anthropic":
            return await self._call_anthropic(messages)
        if provider == "openai":
            return await self._call_openai(messages)
        # Mock fallback — deterministic response for tests
        return json.dumps(
            {
                "cypher": "MATCH (n {user_id: $user_id}) RETURN count(n) AS total",
                "params": {"user_id": str(self._user_id)},
                "explanation": "Mock response: counting user nodes",
            }
        )

    async def _call_anthropic(self, messages: list[dict[str, str]]) -> str:
        from anthropic import AsyncAnthropic

        client = AsyncAnthropic(api_key=self._settings.anthropic_api_key)
        system = messages[0]["content"]
        user_msgs = [m for m in messages[1:] if m["role"] == "user"]
        response = await client.messages.create(
            model=self._settings.agents_specialist_model or "claude-haiku-4-5-20251001",
            max_tokens=1024,
            system=system,
            messages=[{"role": "user", "content": m["content"]} for m in user_msgs],
        )
        return anthropic_text(response.content)

    async def _call_openai(self, messages: list[dict[str, str]]) -> str:
        from openai import AsyncOpenAI
        from openai.types.chat import ChatCompletionMessageParam

        client = AsyncOpenAI(api_key=self._settings.openai_api_key)
        response = await client.chat.completions.create(
            model="gpt-4o-mini",
            messages=cast(list[ChatCompletionMessageParam], messages),
            max_tokens=1024,
            temperature=0.1,
        )
        return str(response.choices[0].message.content)
