"""Prometheus counters for business + system events."""
from __future__ import annotations

from typing import Any

from prometheus_client import Counter, Histogram

user_registered_total = Counter(
    "cvs_user_registered_total", "Total user registrations"
)
logins_total = Counter("cvs_logins_total", "Total successful logins")
cvs_generated_total = Counter(
    "cvs_documents_generated_total", "Total documents generated", ["kind"]
)
cv_generated_total = Counter(
    "cvs_cv_generated_total", "Total CVs generated (business metric)", ["kind"]
)
mcp_invocations_total = Counter(
    "cvs_mcp_invocations_total", "Total MCP tool invocations", ["tool", "ok"]
)
stripe_conversion_total = Counter(
    "cvs_stripe_conversion_total",
    "Total Stripe plan conversions",
    ["plan", "event"],
)
mcp_latency_seconds = Histogram(
    "cvs_mcp_latency_seconds",
    "MCP tool call latency in seconds",
    ["tool"],
)
errors_total = Counter("cvs_errors_total", "Total errors by code", ["code"])

# --- HTTP RED metrics (rate / errors / duration) --------------------------
# `route` MUST be the matched route TEMPLATE (e.g. /api/v1/documents/{id}),
# never the raw path, or label cardinality explodes one series per concrete id.
http_requests_total = Counter(
    "cvs_http_requests_total",
    "HTTP requests",
    ["method", "route", "status"],
)
http_request_duration_seconds = Histogram(
    "cvs_http_request_duration_seconds",
    "HTTP request latency in seconds",
    ["method", "route"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10),
)

# --- Background-task observability ----------------------------------------
# Terminal task failures used to be swallowed (recorded as a successful job).
# This makes the failure modes countable; status in {retry, failed}. See
# src.shared.worker_failures.
task_runs_total = Counter(
    "cvs_task_runs_total",
    "Background task outcomes",
    ["task", "status"],
)


# --- Agentic chat observability -------------------------------------------
# The agentic path had zero token/cost visibility. These let us track run
# volume, latency, error rate, and (where the model exposes it) token spend
# so cost drift and infinite-loop patterns are detectable before they hit a
# provider quota wall.
agent_runs_total = Counter(
    "cvs_agent_runs_total", "Agent/team chat runs", ["agent", "status"]
)
agent_run_seconds = Histogram(
    "cvs_agent_run_seconds", "Agent/team run wall-clock latency", ["agent"]
)
agent_tokens_total = Counter(
    "cvs_agent_tokens_total",
    "LLM tokens consumed by agent runs",
    ["agent", "kind"],
)
# Per-stage latency from the moment the chat request hits the bridge:
# auth_done → validated → team_resolved → intent_done → run_started →
# ttft (first visible text/tool frame) → stream_done. The buckets skew low
# because the optimization target is sub-second TTFT.
agent_stage_seconds = Histogram(
    "cvs_agent_stage_seconds",
    "Elapsed seconds from chat-request start to each pipeline stage",
    ["stage"],
    buckets=(0.05, 0.1, 0.2, 0.35, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0, 5.0, 8.0, 13.0, 21.0),
)

# --- Proposal + discovery observability -----------------------------------
agent_proposals_total = Counter(
    "cvs_agent_proposals_total",
    "Total proposals generated by agents",
    ["entity_type", "action"],
)
agent_proposals_confirmed_total = Counter(
    "cvs_agent_proposals_confirmed_total",
    "Total proposals confirmed by users",
    ["entity_type"],
)
agent_proposals_rejected_total = Counter(
    "cvs_agent_proposals_rejected_total",
    "Total proposals rejected by users",
    ["entity_type"],
)
discovery_entities_extracted_total = Counter(
    "cvs_discovery_entities_extracted_total",
    "Entities extracted from enrichment",
    ["kind"],
)
discovery_esco_links_total = Counter(
    "cvs_discovery_esco_links_total",
    "ESCO links created during enrichment",
    ["state"],
)

_TOKEN_KINDS = (
    "input_tokens",
    "output_tokens",
    "cache_read_tokens",
    "cache_write_tokens",
    "total_tokens",
)


def record_agent_tokens(agent: str, metrics_obj: Any) -> dict[str, int]:
    """Increment token counters from an Agno run `metrics` object.

    Returns a plain dict for structured logging. Safe on None / partial
    objects (e.g. the mock provider exposes no metrics) — never raises, so
    callers can use it without guarding.
    """
    out: dict[str, int] = {}
    if metrics_obj is None:
        return out
    for kind in _TOKEN_KINDS:
        try:
            val = int(getattr(metrics_obj, kind, 0) or 0)
        except (TypeError, ValueError):
            val = 0
        if val:
            agent_tokens_total.labels(agent=agent, kind=kind).inc(val)
        out[kind] = val
    return out
